# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: first.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='first.proto',
  package='proto',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0b\x66irst.proto\x12\x05proto\x1a\x1bgoogle/protobuf/empty.proto\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1d\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x0c\n\nNumRequest\"\x17\n\x08HelloNum\x12\x0b\n\x03num\x18\x01 \x01(\x05\x32t\n\x0c\x46irstGreeter\x12\x34\n\x08SayHello\x12\x13.proto.HelloRequest\x1a\x11.proto.HelloReply\"\x00\x12.\n\x06SayNum\x12\x11.proto.NumRequest\x1a\x0f.proto.HelloNum\"\x00\x62\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_HELLOREQUEST = _descriptor.Descriptor(
  name='HelloRequest',
  full_name='proto.HelloRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='proto.HelloRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=79,
)


_HELLOREPLY = _descriptor.Descriptor(
  name='HelloReply',
  full_name='proto.HelloReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='proto.HelloReply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=81,
  serialized_end=110,
)


_NUMREQUEST = _descriptor.Descriptor(
  name='NumRequest',
  full_name='proto.NumRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=112,
  serialized_end=124,
)


_HELLONUM = _descriptor.Descriptor(
  name='HelloNum',
  full_name='proto.HelloNum',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='num', full_name='proto.HelloNum.num', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=126,
  serialized_end=149,
)

DESCRIPTOR.message_types_by_name['HelloRequest'] = _HELLOREQUEST
DESCRIPTOR.message_types_by_name['HelloReply'] = _HELLOREPLY
DESCRIPTOR.message_types_by_name['NumRequest'] = _NUMREQUEST
DESCRIPTOR.message_types_by_name['HelloNum'] = _HELLONUM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HelloRequest = _reflection.GeneratedProtocolMessageType('HelloRequest', (_message.Message,), {
  'DESCRIPTOR' : _HELLOREQUEST,
  '__module__' : 'first_pb2'
  # @@protoc_insertion_point(class_scope:proto.HelloRequest)
  })
_sym_db.RegisterMessage(HelloRequest)

HelloReply = _reflection.GeneratedProtocolMessageType('HelloReply', (_message.Message,), {
  'DESCRIPTOR' : _HELLOREPLY,
  '__module__' : 'first_pb2'
  # @@protoc_insertion_point(class_scope:proto.HelloReply)
  })
_sym_db.RegisterMessage(HelloReply)

NumRequest = _reflection.GeneratedProtocolMessageType('NumRequest', (_message.Message,), {
  'DESCRIPTOR' : _NUMREQUEST,
  '__module__' : 'first_pb2'
  # @@protoc_insertion_point(class_scope:proto.NumRequest)
  })
_sym_db.RegisterMessage(NumRequest)

HelloNum = _reflection.GeneratedProtocolMessageType('HelloNum', (_message.Message,), {
  'DESCRIPTOR' : _HELLONUM,
  '__module__' : 'first_pb2'
  # @@protoc_insertion_point(class_scope:proto.HelloNum)
  })
_sym_db.RegisterMessage(HelloNum)



_FIRSTGREETER = _descriptor.ServiceDescriptor(
  name='FirstGreeter',
  full_name='proto.FirstGreeter',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=151,
  serialized_end=267,
  methods=[
  _descriptor.MethodDescriptor(
    name='SayHello',
    full_name='proto.FirstGreeter.SayHello',
    index=0,
    containing_service=None,
    input_type=_HELLOREQUEST,
    output_type=_HELLOREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SayNum',
    full_name='proto.FirstGreeter.SayNum',
    index=1,
    containing_service=None,
    input_type=_NUMREQUEST,
    output_type=_HELLONUM,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_FIRSTGREETER)

DESCRIPTOR.services_by_name['FirstGreeter'] = _FIRSTGREETER

# @@protoc_insertion_point(module_scope)
